//Users
export const GET_USERS_STARTED = "GET_USERS_STARTED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

//Account
export const GET_ACCOUNT_STARTED = "GET_ACCOUNT_STARTED"
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE"

//Subscriptions
//True
export const GET_SUBSCRIPTIONS_TRUE_STARTED = "GET_SUBSCRIPTIONS_TRUE_STARTED"
export const GET_SUBSCRIPTIONS_TRUE_SUCCESS = "GET_SUBSCRIPTIONS_TRUE_SUCCESS"
export const GET_SUBSCRIPTIONS_TRUE_FAILURE = "GET_SUBSCRIPTIONS_TRUE_FAILURE"
//False
export const GET_SUBSCRIPTIONS_FALSE_STARTED = "GET_SUBSCRIPTIONS_FALSE_STARTED"
export const GET_SUBSCRIPTIONS_FALSE_SUCCESS = "GET_SUBSCRIPTIONS_FALSE_SUCCESS"
export const GET_SUBSCRIPTIONS_FALSE_FAILURE = "GET_SUBSCRIPTIONS_FALSE_FAILURE"

//Posts
export const GET_POSTS_STARTED = "GET_POSTS_STARTED"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

//Comments
export const GET_COMMENTS_STARTED = "GET_COMMENTS_STARTED"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"