//Users
export const GET_USERS_STARTED = "GET_USERS_STARTED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

//Account
export const GET_ACCOUNT_STARTED = "GET_ACCOUNT_STARTED"
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE"

//