//Users
export const GET_USERS_STARTED = "GET_USERS_STARTED"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

//User
export const GET_USER_ID_STARTED = "GET_USERS_ID_STARTED"
export const GET_USER_ID_SUCCESS = "GET_USERS_ID_SUCCESS"
export const GET_USER_ID_FAILURE = "GET_USERS_ID_FAILURE"

//Account
export const GET_ACCOUNT_STARTED = "GET_ACCOUNT_STARTED"
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE"

//Subscriptions True False
export const GET_SUBSCRIPTIONS_TRUE_STARTED = "GET_SUBSCRIPTIONS_TRUE_STARTED"
export const GET_SUBSCRIPTIONS_TRUE_SUCCESS = "GET_SUBSCRIPTIONS_TRUE_SUCCESS"
export const GET_SUBSCRIPTIONS_TRUE_FAILURE = "GET_SUBSCRIPTIONS_TRUE_FAILURE"
export const GET_SUBSCRIPTIONS_FALSE_STARTED = "GET_SUBSCRIPTIONS_FALSE_STARTED"
export const GET_SUBSCRIPTIONS_FALSE_SUCCESS = "GET_SUBSCRIPTIONS_FALSE_SUCCESS"
export const GET_SUBSCRIPTIONS_FALSE_FAILURE = "GET_SUBSCRIPTIONS_FALSE_FAILURE"

export const SET_SUBSCRIPTIONS_STARTED = "SET_SUBSCRIPTIONS_STARTED"
export const SET_SUBSCRIPTIONS_SUCCESS = "SET_SUBSCRIPTIONS_SUCCESS"
export const SET_SUBSCRIPTIONS_FAILURE = "SET_SUBSCRIPTIONS_FAILURE"

//Posts
export const GET_POSTS_STARTED = "GET_POSTS_STARTED"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

//Comments
export const GET_COMMENTS_STARTED = "GET_COMMENTS_STARTED"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"

export const POST_COMMENTS_STARTED = "POST_COMMENTS_STARTED"
export const POST_COMMENTS_SUCCESS = "POST_COMMENTS_SUCCESS"
export const POST_COMMENTS_FAILURE = "POST_COMMENTS_FAILURE"

//Favorite
export const SET_FAVORITE_STARTED = "SET_FAVORITE_STARTED"
export const SET_FAVORITE_SUCCESS = "SET_FAVORITE_SUCCESS"
export const SET_FAVORITE_FAILURE = "SET_FAVORITE_FAILURE"